### ISSUE TITLE
Decide Sessions for Checkout persist

### ISSUE THREAD

**Issue by knpt** [GH1707-WorkingName/GraceShopper#22]
How should we persist our cart?
Options being considered: 
   - local storage (on window): saved across browser sessions
   - session storage (on window): will only persist until session window is closed
   - save to database (should save to db for signed-in users, but what to save for unauthorized 
          users? session ID + items only when cart is edited? currently our setup is logging all sessions 
          to the db) (dangerous if db is bombarded with cart adds?)
   - redux store (mirrors database like in senior enrichment?)

What does the backend request look like when you add something to your cart?

How to save each item in the cart? Save as an object? (Fellow Sarah indicated this was one of the trickiest issues)

**Comment by gabbysin** [comment]
Per code review conversation w/ @omriBernstein and Francesca: 
- for Unauthenticated users we are going to assign an order.id to the `req.session` when a user "adds" to cart 
- if a pending order is already associated we will GET `req.session.orderId` and use the details to render the pending order details and persist across the same session 
- if one is not already there we will CREATE it, and assign to `req.session.orderId` 

cc/ @knpt @cylau1031 @nicoleivanov

**Comment by omriAckley** [comment]
Glad to see this issue finally resolved, cheers all around!
