### ISSUE TITLE
Modify Database tables to handle expected behavior

### ISSUE THREAD

**Issue by gabby** [GH1707-WorkingName/GraceShopper#35]

**Comment by gabbysin** [comment]
**NOTES FROM DISCUSSION** 

User:
- email
- name (first, last)
- profile img
- address
- isAdmin 

Products:
- title
- description
- img url
- quantity stock
- price 
- tags / categories 

orders: 
- purchase date
- purchase total $ 
- status 

Order details:
- quantity 
(join table) 

Reviews 
- user id / product id 
- description
- date

Order.belongsTo(user)
user.hasMany(user)
Order.belongsToMany(products)
Prodcuts.belongsToMany*orders(
Products.belongsToMany(Reviews) 
User.hasMany(reviews)

**Comment by gabbysin** [comment]
Where are the foreign keys?
