### ISSUE TITLE
Seed the database

### ISSUE THREAD

**Issue by gabbysin** [GH1707-WorkingName/GraceShopper#40]

**Comment by cylau1031** [comment]
const realities = {
  1: {
    title: 'Do You Dare',
    description: 'Ever wonder what it\'s like to be a dare-devil? Experience it first hand with out to risk.',
    imageUrl: 'http://3.bp.blogspot.com/-MmBixjQONj0/UNhJ0hn9_kI/AAAAAAAAC9k/Mim2UkIVnTw/s1600/article-1201105-05C97DC1000005DC-225_634x421.jpg',
    quantity: 10,
    price: 100,
    tags: []
  },
  2: {
    title: 'Spacing Out',
    description: 'The International Space Station is the place to be. Recycled water and air, now that is the life',
    imageUrl: 'https://www.nasa.gov/sites/default/files/thumbnails/image/15618296264_21bc1e368e_o.jpg',
    quantity: 10,
    price: 100,
    tags: []
  },
  3: {
    title: 'Enter Stage Left',
    description: 'Don\'t let the opportunity to rock n roll at Madison Square Garden with your fans.',
    imageUrl: 'https://image.freepik.com/free-photo/rock-band-silhouettes-on-stage-at-concert_1204-416.jpg',
    quantity: 10,
    price: 100,
    tags: []
  },
  4: {
    title: 'Quack',
    description: 'You are the boss rubberduck town.',
    imageUrl: 'http://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1497453970/rubber-duck-florentijn-hofman-DUCKY0617.jpg?itok=4Ydkg_FS',
    quantity: 10,
    price: 100,
    tags: []
  }
}

**Comment by cylau1031** [comment]
`const realities = {
  1: {
    title: 'Do You Dare',
    description: 'Ever wonder what it\'s like to be a dare-devil? Experience it first hand with out to risk.',
    imageUrl: 'http://3.bp.blogspot.com/-MmBixjQONj0/UNhJ0hn9_kI/AAAAAAAAC9k/Mim2UkIVnTw/s1600/article-1201105-05C97DC1000005DC-225_634x421.jpg',
    quantity: 10,
    price: 100,
    tags: []
  },
  2: {
    title: 'Spacing Out',
    description: 'The International Space Station is the place to be. Recycled water and air, now that is the life',
    imageUrl: 'https://www.nasa.gov/sites/default/files/thumbnails/image/15618296264_21bc1e368e_o.jpg',
    quantity: 10,
    price: 100,
    tags: []
  },
  3: {
    title: 'Enter Stage Left',
    description: 'Don\'t let the opportunity to rock n roll at Madison Square Garden with your fans.',
    imageUrl: 'https://image.freepik.com/free-photo/rock-band-silhouettes-on-stage-at-concert_1204-416.jpg',
    quantity: 10,
    price: 100,
    tags: []
  },
  4: {
    title: 'Quack',
    description: 'You are the boss rubberduck town.',
    imageUrl: 'http://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1497453970/rubber-duck-florentijn-hofman-DUCKY0617.jpg?itok=4Ydkg_FS',
    quantity: 10,
    price: 100,
    tags: []
  }
}
 `

**Comment by gabbysin** [comment]
1. title: Burning Man 1, imgUrl: https://www.everfest.com/system/images/W1siZiIsIjIwMTYvMDkvMTQvMTkvMzIvMzUvNjg5L0J1cm5pbmdfTWFuXzIwMTZfQW5kcmV3X0pvcmdlbnNlbl9BcnRfb2ZfYnVybmluZ19tYW5fMjIuanBnIl1d/Burning_Man_2016_Andrew_Jorgensen_Art_of_burning_man_22.jpg

2. title: Burning Man 2, imgUrl:https://stuckincustoms.smugmug.com/Burning-Man/i-fPS7jhQ/0/900x517/Trey%20Ratcliff%20-%20Burning%20Man%20-%20StuckInCustoms%20DOT%20com%20%20-%2044-900x517.jpg

3. title: Cuckoo Cloud Land, imgUrl: https://1.bp.blogspot.com/-pWhUJOR5ahk/WUfaUpBngXI/AAAAAAAAFzs/i1eVSNM-NQsB5lILfhDo7ovsUXzqKtj2gCLcBGAs/s1600/Copywriter.jpg

4. title: Mad Hatter's Tea Part, imgUrl: https://i0.wp.com/writingstudio.co.za/wp-content/uploads/2015/10/alice-in-wonderland-throught-the-looking-glass-cast-and-story-details.jpg 

5. Labryinth Ball, imgurl: https://i.ytimg.com/vi/dFyufUCTCh8/maxresdefault.jpg, 

6. The Chocolate Factory, imgUrl: http://wfiles.brothersoft.com/t/the-chocolate-factory_72421-1920x1200.jpg

**Comment by nicoleivanov** [comment]
Virtual Reality Check
- Get your priorities straight, girl!
https://campustocareer.files.wordpress.com/2013/02/reality-check.jpg

Matrix
- You are the chosen one
https://www.technobuffalo.com/wp-content/uploads/2016/07/matrixreloaded-470x310@2x.png

PuppyVille
- Everyone is a puppy that takes care of themselves, but you get to play with them all day
https://i.pinimg.com/236x/64/24/51/64245141b5d2b30c939dd1fca74180f1--teddy-bears-teddy-bear-dogs.jpg

CandyLand
- Everything is made of candy!
https://i.pinimg.com/originals/00/3c/f3/003cf30e4487bc3826370c5be53aa784.jpg

**Comment by knpt** [comment]
https://images1.laweekly.com/imager/u/original/8035676/abt_pp.jpg

**Comment by knpt** [comment]
http://www.kingwestvets.com/wp-content/uploads/2013/01/puppies-in-a-bathtub.jpg

**Comment by knpt** [comment]
https://regmedia.co.uk/2017/04/24/shutterstock_virtual_reality.jpg?x=1200&y=794
